-
  name: Installing list of packages
  hosts: all
  vars:
    packages:
      - wget
      - make
      - sysstat
      - gcc
  tasks:
    -
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"
